const ADMIN_LOGIN="ADMIN_LOGIN";
const ADMIN_REMOVE="ADMIN_REMOVE";
const ADMIN_LIST="ADMIN_LIST";

const USER_TOTAL = "USER_TOTAL";
const USER_LIST = "USER_LIST";
const PAGE_NO = "PAGE_NO";
const USER_LIKE = "USER_LIKE";
const USER_DIS = "USER_DIS";

const PAGE_AD_NO = "PAGE_AD_NO";
const AD_TOTAL = "AD_TOTAL";
const AD_LIST = "AD_LIST";
const AD_LIKE = "AD_LIKE";
const AD_DIS = "AD_DIS";
const AD_ADD = "AD_ADD";
const AD_SELE = "AD_SELE";

const PAGE_GRO_NO = "PAGE_GRO_NO";
const GRO_TOTAL = "GRO_TOTAL";
const GRO_LIST = "GRO_LIST";
const GRO_LIKE = "GRO_LIKE";
const GRO_DIS = "GRO_DIS";
const GRO_ADD = "GRO_ADD";
const GRO_SELE = "GRO_SELE";
const GRO_DROP_SELE = "GRO_DROP_SELE";

const REL_LIST = "REL_LIST";
const REL_SELE = "REL_SELE";
const REL_UPDATA = "REL_UPDATA";
const REL_DELE = "REL_DELE";
const REL_LIST_COU = "REL_LIST_COU";

const PAGE_LAB_NO = "PAGE_LAB_NO";
const LAB_TOTAL = "LAB_TOTAL";
const LAB_LIST = "LAB_LIST";
const LAB_LIKE = "LAB_LIKE";
const LAB_DIS = "LAB_DIS";
const LAB_ADD = "LAB_ADD";
const LAB_SELE = "LAB_SELE";
const LAB_COU_SELE = "LAB_COU_SELE";
const LAB_DROP_SELE = "LAB_DROP_SELE";

const PAGE_TEA_NO = "PAGE_TEA_NO";
const TEA_TOTAL = "TEA_TOTAL";
const TEA_LIST = "TEA_LIST";
const TEA_LIKE = "TEA_LIKE";
const TEA_DIS = "TEA_DIS";
const TEA_ADD = "TEA_ADD";
const TEA_SELE = "TEA_SELE";
const TEA_COU_SELE = "TEA_COU_SELE";
const TEA_DROP_SELE = "TEA_DROP_SELE";

const RIN_OPTION = "RIN_OPTION";
const PAGE_RIN_NO = "PAGE_RIN_NO";
const RIN_TOTAL = "RIN_TOTAL";
const RIN_LIST = "RIN_LIST";
const RIN_LIKE = "RIN_LIKE";
const RIN_DIS = "RIN_DIS";
const RIN_SELE = "RIN_SELE";
const RIN_COU_SELE = "RIN_COU_SELE";
const RIN_GRO_SELE = "RIN_GRO_SELE";
const RIN_DROP_SELE = "RIN_DROP_SELE";

const PAGE_COU_NO = "PAGE_COU_NO";
const COU_TOTAL = "COU_TOTAL";
const COU_LIST = "COU_LIST";
const COU_LIKE = "COU_LIKE";
const COU_DIS = "COU_DIS";
const COU_SELE = "COU_SELE";

const CHICOU_TOTAL = "CHICOU_TOTAL";
const CHICOU_LIST = "CHICOU_LIST";
const PAGE_CHICOU_NO = "PAGE_CHICOU_NO";
const CHICOU_LIKE = "CHICOU_LIKE";
const CHICOU_UPDATA = "CHICOU_UPDATA";
const CHICOU_DIS = "CHICOU_DIS";
const CHICOU_DELE = "CHICOU_DELE";
const CHICOU_SELE = "CHICOU_SELE";


const GLO_SELE_PZ = "GLO_SELE_PZ";

export default {
	ADMIN_LOGIN,
	ADMIN_REMOVE,
	ADMIN_LIST,
	USER_TOTAL,
	USER_LIST,
	PAGE_NO,
	USER_LIKE,
	USER_DIS,
	PAGE_AD_NO,
	AD_TOTAL,
	AD_LIST,
	AD_LIKE,
	AD_DIS,
	AD_ADD,
	AD_SELE,
	PAGE_GRO_NO,
	GRO_TOTAL,
	GRO_LIST,
	GRO_LIKE,
	GRO_DIS,
	GRO_ADD,
	GRO_SELE,
	GRO_DROP_SELE,
	REL_LIST,
	REL_SELE,
	REL_UPDATA,
	REL_DELE,
	REL_LIST_COU,
	PAGE_LAB_NO,
	LAB_TOTAL,
	LAB_LIST,
	LAB_LIKE,
	LAB_DIS,
	LAB_ADD,
	LAB_SELE,
	LAB_COU_SELE,
	LAB_DROP_SELE,
	PAGE_TEA_NO,
	TEA_TOTAL,
	TEA_LIST,
	TEA_LIKE,
	TEA_DIS,
	TEA_ADD,
	TEA_SELE,
	TEA_COU_SELE,
	TEA_DROP_SELE,
	RIN_OPTION,
	PAGE_RIN_NO,
	RIN_TOTAL,
	RIN_LIST,
	RIN_LIKE,
	RIN_DIS,
	RIN_SELE,
	RIN_COU_SELE,
	RIN_GRO_SELE,
	RIN_DROP_SELE,
	PAGE_COU_NO,
	COU_TOTAL,
	COU_LIST,
	COU_LIKE,
	COU_DIS,
	COU_SELE,
	CHICOU_TOTAL,
	CHICOU_LIST,
	PAGE_CHICOU_NO,
	CHICOU_LIKE,
	CHICOU_UPDATA,
	CHICOU_DIS,
	CHICOU_DELE,
	CHICOU_SELE,
	GLO_SELE_PZ
}